name: flutterrtdeliveryboyapp
description: A new Flutter Restaurant Delivery Boy application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.4.0+17
publish_to: none

# CCV 2.4 = 2.4.0+17
# CCV 2.3 = 2.3.0+14
# CCV 2.2 = 2.2.0+13
# CCV 2.1 = 2.1.0+12
# CCV 2.0 = 2.0.0+11
# CCV 1.9 = 1.9.0+10
# CCV 1.8 = 1.8.0+9
# CCV 1.7 = 1.7.0+8
# CCV 1.6 = 1.6.0+7
# CCV 1.5 = 1.5.0+6
# CCV 1.4 = 1.4.0+5
# CCV 1.3 = 1.3.0+4
# CCV 1.2 = 1.2.0+3
# CCV 1.1 = 1.1.0+2
# CCV 1.0 = 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependency_overrides:
  intl: any
dependencies:



  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  platform: ^3.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  connectivity: 3.0.6
  shimmer: ^3.0.0
  slider_button: 2.1.0
  swipeable_button_view: ^0.0.2
  cached_network_image: ^3.3.1
  theme_manager: 1.1.1
  flutter_map: 5.0.0
  page_transition: ^2.1.0
  image_picker: ^1.0.7
  easy_localization: ^3.0.3
  latlong2: ^0.9.0
  sembast: ^3.5.0+1
  path_provider: ^2.1.2
  intl: 0.17.0
  url_launcher: ^6.2.3
  firebase_core: ^2.24.2
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.16.0
  google_mobile_ads: ^4.0.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.3
  flutter_speed_dial: ^7.0.0
  progress_dialog_null_safe: 1.0.7
  launch_review: 3.0.1
  package_info_plus: ^4.2.0
  fluttericon: 2.0.0 
  fluttertoast: ^8.2.4
  permission_handler: ^11.0.1
  the_apple_sign_in: 1.1.1
  geolocator: ^10.1.0
  photo_view: 0.14.0
  flutter_widget_from_html: ^0.14.11
  flutter_native_image: 0.0.6+1
  share_plus: ^7.2.1
  geocoding: ^2.1.1
  firebase_crashlytics: ^3.4.9
  quiver: ^3.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_local_notifications:
  #  path: lib/utils/local_noti/

  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/placeholder_image.png
   - assets/langs/ar-DZ.json
   - assets/langs/en-US.json
   - assets/langs/hi-IN.json
   - assets/langs/de-DE.json
   - assets/langs/es-ES.json
   - assets/langs/fr-FR.json
   - assets/langs/id-ID.json
   - assets/langs/it-IT.json
   - assets/langs/ja-JP.json
   - assets/langs/ko-KR.json
   - assets/langs/ms-MY.json
   - assets/langs/pt-PT.json
   - assets/langs/ru-RU.json
   - assets/langs/th-TH.json
   - assets/langs/tr-TR.json
   - assets/langs/zh-CN.json
   - assets/images/verify_email_icon.jpg
   - assets/images/empty_active_delivery.png
   - assets/images/app_icon.png
   - assets/images/user_default_photo.png
   - assets/images/salad.png
   - assets/images/seo.png
   - assets/images/burger.png
   



   
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
